---
name: Acme-6502
version: 0.76

author:
  - 'Andy Armstrong <andy@hexten.net>'
abstract: Pure Perl 65C02 simulator.
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Acme-6502
  license: http://dev.perl.org/licenses/
  repository: git://github.com/AndyA/Acme--6502.git
requires:
  Class::Std: 0
  Class::Std::Slots: 0
  Term::ReadKey: 0
  Test::More: 0
  version: 0
provides:
  Acme::6502:
    file: lib/Acme/6502.pm
    version: 0.75
  Acme::6502::Tube:
    file: lib/Acme/6502/Tube.pm
    version: 0.75
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
